language: android

env:
  global:
    - ANDROID_API_LEVEL=25
    - EMULATOR_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis

android:
  components:
    # To build your project with the SDK Platform Tools revision 24 or above, you need to define the
    # following components
    # Note that the tools section appears twice on purpose as it’s required to get the newest
    # Android SDK tools.
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL

    # For Google APIs
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$EMULATOR_API_LEVEL

    # Google Play Services
    - extra-google-google_play_services

    # Support library
    - extra-android-support

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL

  licenses:
    - android-sdk-license-.+
    - ".+"

before_install:
  - chmod +x gradlew
#  https://github.com/travis-ci/travis-ci/issues/8874
  - yes | sdkmanager "platforms;android-26"

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean assembleDebug test connectedDebugAndroidTest